export interface FlaggedJob {
  id: number;
  client: string;
  client_id: number;
  device: string;
  device_id: number;
  job_name: string;
  source: string;
  failures_this_window: number;
  consecutive_failures: number;
  failure_pct: number;
  last_failure: string | null;
  first_seen: string | null;
  rule_triggered: 'count' | 'consecutive' | 'pct';
  error_reason: string;
  proposed_solution: string;
  ticket_created: boolean;
  ticket_id: string | null;
}

export interface ProblemConfig {
  scope_msp_id: number | null;
  scope_client_id: number | null;
  scope_device_id: number | null;
  scope_msp_ids: number[];
  excluded_client_ids: number[];
  excluded_device_ids: number[];
  time_window: 'weekly' | 'monthly' | 'rolling_7' | 'rolling_30';
  failure_count_threshold: number;
  consecutive_threshold: number;
  failure_pct_threshold: number;
  auto_create_ticket: boolean;
  dedupe_tickets: boolean;
  auto_resolve: boolean;
  append_notes: boolean;
  psa_provider: string;
  psa_board: string;
  psa_priority: string;
  psa_ticket_type: string;
  psa_assign_to: string;
  psa_sla: string;
  psa_status_on_create: string;
  title_template: string;
  body_template: string;
  custom_fields: { fieldName: string; value: string; notes: string }[];
  email_alert: boolean;
  email_address: string;
  teams_alert: boolean;
  webhook_url: string;
}

export const PSA_CONFIG: Record<string, {
  name: string;
  boardLabel: string;
  typeLabel: string;
  priorityLabel: string;
  boards: string[];
  types: string[];
  priorities: string[];
  statuses: string[];
}> = {
  connectwise: {
    name: 'ConnectWise Manage',
    boardLabel: 'Service board',
    typeLabel: 'Type',
    priorityLabel: 'Priority',
    boards: ['Service Desk – Tier 2', 'NOC Operations', 'Backup & Recovery', 'Critical Alerts'],
    types: ['Incident', 'Problem', 'Alert', 'Service Request'],
    priorities: ['Low', 'Medium', 'High', 'Critical'],
    statuses: ['New', 'In Progress', 'Waiting on Parts', 'Assigned'],
  },
  halopsa: {
    name: 'HaloPSA',
    boardLabel: 'Team / Queue',
    typeLabel: 'Ticket category',
    priorityLabel: 'Priority',
    boards: ['NOC Team Queue', 'Backup Specialists', 'Tier 2 Support', 'Escalations'],
    types: ['Incident', 'Problem', 'Change', 'Service Request'],
    priorities: ['Low', 'Medium', 'High', 'Critical'],
    statuses: ['New', 'In Progress', 'Waiting', 'Assigned'],
  },
  autotask: {
    name: 'Autotask',
    boardLabel: 'Queue',
    typeLabel: 'Issue type',
    priorityLabel: 'Priority',
    boards: ['Service Desk', 'Network Operations', 'Backup & DR Queue', 'Priority Response'],
    types: ['Incident', 'Problem', 'Change Request', 'Service Request'],
    priorities: ['Low', 'Medium', 'High', 'Critical'],
    statuses: ['New', 'In Progress', 'Waiting Customer', 'Assigned'],
  },
  freshservice: {
    name: 'Freshservice',
    boardLabel: 'Group',
    typeLabel: 'Ticket type',
    priorityLabel: 'Urgency',
    boards: ['IT Support', 'Infrastructure Team', 'Backup & Recovery Group', 'On-Call Team'],
    types: ['Incident', 'Service Request', 'Problem', 'Change'],
    priorities: ['Low', 'Medium', 'High', 'Critical'],
    statuses: ['Open', 'In Progress', 'Pending', 'Assigned'],
  },
};

export function defaultConfig(): ProblemConfig {
  return {
    scope_msp_id: null,
    scope_client_id: null,
    scope_device_id: null,
    scope_msp_ids: [],
    excluded_client_ids: [],
    excluded_device_ids: [],
    time_window: 'weekly',
    failure_count_threshold: 3,
    consecutive_threshold: 2,
    failure_pct_threshold: 50,
    auto_create_ticket: true,
    dedupe_tickets: true,
    auto_resolve: false,
    append_notes: true,
    psa_provider: 'connectwise',
    psa_board: 'Service Desk – Tier 2',
    psa_priority: 'Medium',
    psa_ticket_type: 'Problem',
    psa_assign_to: 'Unassigned',
    psa_sla: 'Standard SLA – 4 hr',
    psa_status_on_create: 'New',
    title_template: '[Backup Problem] {client} — {device} · {job} · {failure_count} failures',
    body_template:
      'Backup problem detected by BackupPulse.\n\n' +
      'Client:               {client}\n' +
      'Device:               {device}\n' +
      'Job:                  {job}\n' +
      'Source:               {source}\n' +
      'Failures in {window}: {failure_count}\n' +
      'Consecutive failures: {consecutive_count}\n' +
      'Last failure:         {last_seen}\n' +
      'First detected:       {first_seen}\n\n' +
      'ERROR\n{error_reason}\n\n' +
      'PROPOSED SOLUTION\n{proposed_solution}\n\n' +
      '---\nAuto-generated by BackupPulse. Please investigate and resolve.',
    custom_fields: [
      { fieldName: 'backup-source', value: '{source}', notes: 'Used for duplicate check' },
      { fieldName: 'backup-client', value: '{client}', notes: 'De-duplication key' },
      { fieldName: 'backup-device', value: '{device}', notes: 'De-duplication key' },
      { fieldName: 'backup-job',    value: '{job}',    notes: 'De-duplication key' },
      { fieldName: 'problem-type',  value: 'backup',   notes: 'Fixed tag' },
    ],
    email_alert: true,
    email_address: 'noc@company.com',
    teams_alert: false,
    webhook_url: '',
  };
}

export function windowLabel(w: string): string {
  return (
    { weekly: 'this week', monthly: 'this month', rolling_7: 'in the last 7 days', rolling_30: 'in the last 30 days' }[w] ?? 'this week'
  );
}
